Dg service http
GonzalD/Iolearn pull request #8
Opened 2016-11-24 23:50 UTC by GonzalD

J'ai créé le service qui récupère par défaut les information de l'API depuis un fichier local.
J'ai une fonction toute prête qui peut aussi recueillir les données sur le webservice et qui fonctionne quand je le teste dans mon navigateur avec un module qui accepte le "Cross-origin ressource sharing".
J'ai pas encore pu faire marcher la fonction pour whitelister la requête (avec JSONP).

Le tout est envoyé au controlleur qui le récupère et l'affiche dans une liste. (voir branche dg-controller-use-service)

J'ai aussi ajouté des fichier comme app.js dans lesquels j'ai intégré les modules correspondant pour faire marcher le tout.

Pour tester le tout il faut pull cette branche-ci et celle du controller.

2016-11-24 23:53 UTC, GonzalD commented
![](https://github.trello.services/images/mini-trello-icon.png) [[angular] apprentissage des services (sera utilisé par les controllers et les vues/directives)](https://trello.com/c/Lz6kuVXB/9-angular-apprentissage-des-services-sera-utilise-par-les-controllers-et-les-vues-directives)

2016-12-08 13:41 UTC, evaletolab requested changes

2016-12-08 13:41 UTC, evaletolab commented on www/js/http.service.js
> +  function getProducts($http) {
Si le but de ton service c'est de donner la liste des produits laitier => alors ton service doit s'appeler milkService :+1:

2016-12-08 13:41 UTC, evaletolab commented on www/js/http.service.js
> +    };
A nouveau, si ton service c'est milkService => alors la méthode c'est milkService.get tu peux créer une méthode milkService.configure(useHttp:true||false) pour configurer le backend file ou http

2016-12-17 14:12 UTC, evaletolab approved these changes

2016-12-17 14:12 UTC, merged