creation controller de produit laitier + template de l'onglet produit…
GonzalD/Iolearn pull request #9
Opened 2016-11-24 23:52 UTC by GonzalD

Cette branche contient le controleur avec le template html de l'onglet, son fichier css, etc.
…, integration dans index.html et fichier css utilisé
Pour l'instant j'ai juste mis une barre de recherche et la possibilité de cliquer pour dévoiler d'autres informations sur les items de la liste.

J'ai commencé à coder la possibilité d'afficher uniquement un certain nb d'élément de la liste par page et pouvoir naviguer par "swipe" à gauche et à droite. Pour l'instant ça ne fait que changer le numero de page mais l'affichage ne change pas car je dois créer un filtre pour faire fonctionner ça.

Il manque aussi le bouton pour acheter et d'autres information à afficher dynamiquement (produit bio, local, vegetarien et autres).

A tester avec la branche dg-service-http ;)

2016-11-24 23:54 UTC, GonzalD commented
![](https://github.trello.services/images/mini-trello-icon.png) [[angular] apprentissage du controller](https://trello.com/c/OA3GMvGj/8-angular-apprentissage-du-controller)

2016-12-08 13:42 UTC, evaletolab requested changes

2016-12-08 13:42 UTC, evaletolab commented on www/js/http.controller.js
> +    var url = 'http://api.karibou.evaletolab.ch/v1/products/category/produits-laitiers';
pourquoi tu ne mets pas l'url:L16 dans le service ? et ton service tu le types milkProducts,

2016-12-08 13:42 UTC, evaletolab commented on www/js/http.controller.js
> +    function getFromFile(){
ça aussi, c'est a configurer dans le service! getFromFile doit être caché par le service :+1:

2016-12-08 13:42 UTC, evaletolab commented on www/js/http.controller.js
> +    function getFromAPI(){
même chose avec getFromApi (check le PR du service)

2016-12-17 14:14 UTC, evaletolab approved these changes

2016-12-17 14:14 UTC, evaletolab commented on www/js/http.controller.js
> +  function ProduitsCtrl($scope, $http, milkService){
Franglais? :smile:

2016-12-17 14:14 UTC, evaletolab commented on www/js/http.controller.js
> +    milkService.configure(false);
c'est toujours mieux d'utiliser un object pour la config {machin:true, ... }

2016-12-17 14:14 UTC, merged